spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 39.98.240.253:9300
#      cluster-nodes: 192.168.72.120:9300

dubbo:
  application:
    name: search-services
    owner: gp-search
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: zookeeper://zk.gpmall.com:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://zk.gpmall.com:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com